### ISSUE TITLE
Window title should display score.

### ISSUE THREAD

**Issue by za419** [Murfalo/Polly#12]
It would be nice if the window title kept track of the current score.

**Comment by Murfalo** [comment]
I'm not sure if there is a reasonable way to update the title frequently.  We could more realistically add a score to the top right corner or something of the sort.

**Comment by za419** [comment]
I'd say that the scoreboard added in e34da02ec5494f19a38d619d5e4c4b843650c532 has fixed this. It can be re-opened if we find a way to do this better.
