### ISSUE TITLE
Add more static collectables

### ISSUE THREAD

**Issue by za419** [Murfalo/Polly#17]
There shouldn't be too many, but I think there should be certain spots on the map that should always have collectables - In the corners of circle obstacles, for example (as the current random positioning implemented in 5929893b8796a3ad5e9863b082fce07bf26d8017 often un-fixes #5 )

**Comment by Murfalo** [comment]
There is a row of collectibles on the bottom that always spawns a collectible.  If you want more, I can definitely get that done sometime.

**Comment by za419** [comment]
I noted that. I was thinking more in the area we talked about (where you can go because of the cool circle collisions that you can't otherwise), because right now that doesn't always seem to happen and that removes the whole showing off those colliders thing

**Comment by za419** [comment]
Fixed by @Murfalo
