### ISSUE TITLE
Wall bounding boxes are slightly too large

### ISSUE THREAD

**Issue by Murfalo** [Murfalo/Polly#9]
Title; very dissatisfying as the player to die when you did not appear to touch the walls

**Comment by Murfalo** [comment]
There is the potential that the problem is actually Polly's bounding box rather than the wall's.

**Comment by za419** [comment]
It is not Polly's box, that much is clear by collisions with circles

**Comment by za419** [comment]
Fixed by commit e605cf4033e4f639e970a9aeca4cb7ce2ee4e454, made by @Murfalo . Many thanks

**Comment by za419** [comment]
Forensic tracking - This was introduced in 3e69a136c189990214e55088b1a5abd893f02e11, when @Murfalo and I made the walls thinner without making the bounding box thinner. Oops!
